sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: gthAglb6nosfuc6mNdt1p0gng6qNbivOrJC3bBGgywz5eBO2P0RZ5fFUpUZw4FsVnq/kvzL4qz/fTiPrgK17epYhHrKcfS5TGntYIRswcSD3HSbBk0Bm9PPMjEuQOpGuxkFqIxgAc+fJDTbzH8pqyrfTWmXCbUPGEiZdYhuiIm2Dn0Ht3RDA8DVLeInY7+6CK0Ca4+ipKt9dw1EisHb7EHTKALFxF01fAwx9ptB9Ary8iCXcJVs42/GSZTesyltMoYIhM7vMfN+hP3ocgzoxpr4meucIpoeV9GM6gwf2tkiuVa+H2W+/tfNoTwiEIrq06lPOeaDt0sTVh6aOfY6vdUmEDxavPXBzadk+y1iFyZoGCmrh3jwodHZr2hhh0rODQE9fpUFDFkJLJDA29i0fmwCfzFZKZ8yzrETBPrr1uUzHQx9X+5ILsKof2PL09hbBnXt4CUX39nwCtOE6kDmuv9hUOUE2ByOXhbTn/vsL6WXdCjBLPZYzFDNHBU9n3geErOrvFf3IScprfmmEnleD7uaQNa+Mm1k02oZna/nbMPhZOma2e7zkwVwKvDgZGOip6x6tCsk+Dh+F5op25RjBnQml0ba+XvL4LaE+uJAcWux/1OeVdLrUHUXqb/G9LLc6vc0tLwmBgPSjOXV16unvCigmwDJpVspgeoWZdsdeMYA=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Girl-from-Keller-s_3663
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy